pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/get-votes/', views.get_votes, name='get_votes'),
    path('<int:question_id>/chart/', views.chart, name='chart'),
    path('generate-gamers/', views.generate_gamers_in_db, name='generate_gamers_in_db'),
    path('json-gamers/', views.get_gamers_json, name='get_gamers_json'),
    path('raw-chart-gamers/', views.raw_gamer_chart, name='raw_gamer_chart')
]

sandbox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    created_at = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Gamer(models.Model):
    avatar_name = models.CharField(max_length=200)
    playtime = models.IntegerField()
    money_spent = models.IntegerField()

    def __str__(self):
        return self.avatar_name

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.forms.models import model_to_dict
import random

from .models import Question, Choice, Gamer


# Get questions and display them
def index(request):
    question_list = Question.objects.all()
    context = {'question_list': question_list}
    return render(request, 'polls/index.html', context)


# Show specific question and choices
def detail(request, question_id):
  try:
    question = Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'polls/detail.html', { 'question': question })


# Get question and display results
def results(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'polls/results.html', { 'question': question })

# Vote for a question choice
def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# Provide vote results in json format
def get_votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = []
    for choice in question.choice_set.all():
        choices.append(model_to_dict(choice))
    return JsonResponse(choices, safe=False)


# Display chart page
def chart(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/chart.html', { 'question': question })


# Add a set of gamer entries to DB
def generate_gamers_in_db(request):

    return JsonResponse({"warning":"this command will generate 50k entries in db. If you want to execute it, update polls -> views -> generate_gamers_in_db"}, safe=False)

    avatar_name_suffix = avatar_name_core = avatar_name_prefix = ["Slayer", "Doom", "Mighty", "Magic", "Elf", "Dwarf", "Eagle", "Sword", "Gun", "Blast", "Fire", "Lord", "Warior", "Mage", "Rogue", "War", "Battle", "Champion", "Team", "Chosen"]
    for i in range(10000): # play few pay few
      gamer = Gamer()
      gamer.avatar_name = avatar_name_suffix[random.randint(0,19)] + avatar_name_core[random.randint(0,19)] + avatar_name_prefix[random.randint(0,19)]
      gamer.playtime = random.randint(1,100)
      gamer.money_spent = random.randint(1,10)
      gamer.save()

    for i in range(20000): # play lot pay few
      gamer = Gamer()
      gamer.avatar_name = avatar_name_suffix[random.randint(0,19)] + avatar_name_core[random.randint(0,19)] + avatar_name_prefix[random.randint(0,19)]
      gamer.playtime = random.randint(100,1000)
      gamer.money_spent = random.randint(1,10)
      gamer.save()
    
    for i in range(12000): # play lot pay lot
      gamer = Gamer()
      gamer.avatar_name = avatar_name_suffix[random.randint(0,19)] + avatar_name_core[random.randint(0,19)] + avatar_name_prefix[random.randint(0,19)]
      gamer.playtime = random.randint(100,1000)
      gamer.money_spent = random.randint(10,100)
      gamer.save()

    for i in range(8000): # play few pay lot
      gamer = Gamer()
      gamer.avatar_name = avatar_name_suffix[random.randint(0,19)] + avatar_name_core[random.randint(0,19)] + avatar_name_prefix[random.randint(0,19)]
      gamer.playtime = random.randint(1,100)
      gamer.money_spent = random.randint(10,100)
      gamer.save()

    # return JsonResponse({"resonse":"ok"}, safe=False)


# Display chart page for all gamers
def raw_gamer_chart(request):
    return render(request, 'polls/raw_gamer_chart.html', {})


# Get JSON data of all gamers
def get_gamers_json(request):
    gamers_data = []
    for gamer in Gamer.objects.all():
        gamers_data.append(model_to_dict(gamer))
    return JsonResponse(gamers_data, safe=False)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Pollster {% block title %}{% endblock %}</title>
</head>
<body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome To Pollster</h1>
    <p>This is an example Django polling app</p>
    <a class="btn btn-dark" href="{% url 'polls:index' %}">
        View Available Polls</a
      >
  </div>
  </div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Pollster</a>
		<a class="navbar-brand" href="{% url 'polls:get_gamers_json' %}">Gamers JSON</a>
		<a class="navbar-brand" href="{% url 'polls:raw_gamer_chart' %}">Gamers chart</a>
	</div>
</nav>

templates/polls/chart.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
<div class="row justify-content-center">
<canvas id="myChart" data-url="{% url 'polls:get_votes' question.id %}" width="400" height="400"></canvas>
</div>
<div class="row">
<div class="col-sm">
<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
</div>
<div class="col-sm">
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
<div class="col-sm">
<a href="{% url 'polls:results' question.id %}" class="btn btn-dark">Results</a>
</div>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'js/chart.js' %}"></script>
{% endblock %}

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %} 
{% block content %} 
  <h1 class="text-center mb-3">Poll Questions</h1>
  {% if question_list %}
    {% for question in question_list %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ question.question_text }}</p>
          <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
          <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{% endblock %}

templates/polls/raw_gamer_chart.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">Gamers</h1>
<div class="row justify-content-center">
<canvas id="myChart" data-url="{% url 'polls:get_gamers_json' %}" width="400" height="400"></canvas>
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'js/raw_gamer_chart.js' %}"></script>
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a class="btn btn-dark" href="{% url 'polls:chart' question.id %}">View chart</a>
{% endblock %}